name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: snapsnatch

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run tests
        run: mvn test -Pci
        env:
          SPRING_PROFILES_ACTIVE: ci
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/snapsnatch
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: root

#     Dependency Tree Submission with Dependabot keeps failing, so I have commented it out for now

#      - name: Maven Dependency Tree Dependency Submission for Dependabot
#        if: github.actor == 'dependabot[bot]'
#        uses: advanced-security/maven-dependency-submission-action@v4.0.2
#        with:
#          ignore-maven-wrapper: true
#          token: ${{ secrets.dependency_tree_token }}
#
#      - name: Maven Dependency Tree Dependency Submission for Others
#        if: github.actor != 'dependabot[bot]'
#        uses: advanced-security/maven-dependency-submission-action@v4.0.2
#        with:
#          ignore-maven-wrapper: true
#          token: ${{ secrets.GITHUB_TOKEN }}
