name: Release Workflow

on:
  workflow_run:
    workflows: ["Java CI with Maven"]
    types:
      - completed
    branches:
      - main
    paths:
      - 'pom.xml'

jobs:
  release:
    runs-on: ubuntu-latest
    if: env.VERSION_CHANGED == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Get the current POM version
        run: |
          CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Validate if tag exists
        run: |
          if git rev-parse "$CURRENT_VERSION" >/dev/null 2>&1; then
            echo "TAG_EXISTS=true" >> $GITHUB_ENV
          else
            echo "TAG_EXISTS=false" >> $GITHUB_ENV

      - name: Create Release
        if: env.TAG_EXISTS == 'false'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.CURRENT_VERSION }}
          release_name: Release ${{ env.CURRENT_VERSION }}
          draft: false
          prerelease: ${{ contains(env.CURRENT_VERSION, 'SNAPSHOT') }}
