name: Release Workflow

on:
  push:
    branches:
      - main
    paths:
      - '**/pom.xml'

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Adjust this to your project's JDK version
          distribution: 'temurin'

      - name: Get the current POM version
        run: |
          echo "CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Check if any tags exist
        id: check_tags
        run: |
          if git rev-list --tags --max-count=1 2>/dev/null; then
            echo "TAG_EXISTS=true" >> $GITHUB_ENV
          else
            echo "TAG_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Get latest tag
        if: env.TAG_EXISTS == 'true'
        run: |
          echo "LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV

      - name: Set default version if no tags
        if: env.TAG_EXISTS == 'false'
        run: |
          echo "LATEST_TAG=0.0.1" >> $GITHUB_ENV  # Set your default initial version here

      - name: Check for version change
        run: |
          if [ "$CURRENT_VERSION" == "$LATEST_TAG" ]; then
            echo "No version change detected in pom.xml, skipping release."
            exit 0
          fi

  release:
    needs: check-version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Adjust this to your project's JDK version
          distribution: 'temurin'

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.CURRENT_VERSION }}
          release_name: Release ${{ env.CURRENT_VERSION }}
          draft: false
          prerelease: false
